### Sign up
POST http://localhost:3007/auth/signup
content-type: application/json

{
  "email": "ivanov.ivan.01@gmail.com",
  "password": "12312",
  "passwordRepeat": "12312"
}

### Login
# @no-cookie-jar
POST http://localhost:3007/auth/login
content-type: application/json

{
  "email": "ivanov.ivan.01@gmail.com",
  "password": "12312"
}

### Update
PUT http://localhost:3007/auth/update
content-type: application/json
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0ZjU1Mzg2LWNiMzYtNDUyZi1iZGVlLTc1NjI5NDNiNWY2YiIsImVtYWlsIjoiaXZhbm92Lml2YW4uMDFAZ21haWwuY29tIiwicm9sZXMiOlsiVVNFUiJdLCJpYXQiOjE3NTY5MDA4OTAsImV4cCI6MTc1NzUwNTY5MH0.CcGBI6tZovBF7m7cL2kstlgwHLGXb5ilyjCZ9d1Wp_E

{

  "email": "ivanov.ivan.01@gmail.com",
  "roles": ["ADMIN"]
}